[package]
name = "tetra_test"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.28.0", features = ["rand"] }
rstar = "0.12.0"
[dev-dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
