[package]
name = "tetra_test"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.28.0", features = ["rand"] }
kiddo = { version = "4.2.0", features = ["rayon"] }
rand = "0.8.5"
rand_distr = "0.4.3"
